### ISSUE TITLE
The signing algorithm hashes twice

### ISSUE THREAD

**Issue by kubasiemion** [hyperledger/avalon#120]
We have been having some mysterious difficulties in preparing an acceptable WorkOrderSubmit request in pure python or golang (i.e. without using the swig library). Turns out the digest of the request is hashed TWICE:

first in _signature.py()_:
`262 final_hash = crypto.compute_message_hash(concat_hash)`
[...]
`270 status, signature = self.generate_signature(final_hash, private_key)`

and then down the frame stack from generate_signature, in _sig_private_key.cpp()_:
212 `ByteArray pcrypto::sig::PrivateKey::SignMessage(const ByteArray& message) const {`
213 ` unsigned char hash[SHA256_DIGEST_LENGTH];`
214       ` // Hash`
215       `SHA256((const unsigned char*)message.data(), message.size(), hash);`
[...]
A compensating hashing is done in the openssl wrapper during signature verification, so if one uses that library both on the server and in the client, it does not show.
But when using other libraries/languages, it is becoming awkward (and is not documented) - one has to:
- concatenate the relevant parts of a request
- calculate sha256 of this extract --> h1
- encrypt the resulting  hash and include it in the request
- calculate sha256 of the hash h1 --> h2
- sign the hashed hash h2 with some private key
- include the signature and the public key in the request

This is counter-intuitive and not documented.
Same happens during verification: one needs to decrypt the hash, recover the signature, and then verify the signature against the *hash of the hash*. 
If this is intentional, it should be very well documented at the least.

**Comment by manojgop** [comment]
@kubasiemion This is a good catch. This behavior fror signMessage() function is due to a legacy code taken from https://github.com/hyperledger-labs/private-data-objects/. I've raised a PR https://github.com/hyperledger-labs/trusted-compute-framework/pull/127 to avoid hashing twice.

**Comment by arsulegai** [comment]
I am curious here and would like to understand in greater detail, why is this done like the way it is there today. Correct me as I am new to this framework

- concatenate the relevant parts of a request
- calculate sha256 of this extract --> h1
- encrypt the resulting hash and include it in the request
  [Arun] I guess the encryption key spoken about here is a symmetric key, and is shared only with the enclave. This is a proof to the enclave about message integrity.

- calculate sha256 of the hash h1 --> h2
- sign the hashed hash h2 with some private key
- include the signature and the public key in the request
  [Arun] Generally public key of the requester should be known to the enclave as a priori. Otherwise, it is possible to attack the enclave (at least DoS) and fail the requests. The signature is sent along with the public key to verify it. It would at least help if the signature is calculated on encrypted(hash(message)) which is encrypted(h1). This way there is link between message -> digest -> encrypted digest -> signature. The final information gained by the enclave is the public key of the requester.

Another question out of curiosity, what is the public key of the requester used for?

**Comment by manojgop** [comment]
@arsulegai You can refer to https://entethalliance.github.io/trusted-computing/spec.html#work-order-signing.

**Comment by arsulegai** [comment]
Right! the line "**Distribution of the corresponding public keys is outside of the scope of this specification**" clarifies. So, in case of HL Avalon/TCF the implementation is to rely on the encryptedSessionKey to share the public key.

i.e. Instead of sign(message), it should be sign(encrypted(hash(message))). In other words sign(encrypted(h1)) from previous comment I pasted. This way public key can be safely shared.

**Comment by manojgop** [comment]
As mentioned in spec, there are two mechanisms ensuring the integrity of a work order request:

1. encryptedRequestHash contains the hash of the work order request encrypted with a key from encryptedSessionKey. This mechanism ensures the request integrity even in the case of an anonymous requester. The hash value in this case is verified by the worker.

2. requesterSignature is an optional signature that uses the same calculated hash value and signs it with the requester's private signing key
