### ISSUE TITLE
Can't find avalon-blockchain-connector-dev docke image

### ISSUE THREAD

**Issue by Hackadon-crypto** [hyperledger/avalon#655]
I wanted to deploy avalon through k8s and used the scripts in avalon/docker/k8s/fabric/blockchain-connector.yaml.
This depends on avalon-blockchain-connector-dev image, but I haven't built it.
'''
spec:
      containers:
      - image: avalon-blockchain-connector-dev:latest
        name: avalon-blockchain-connector
'''
How to build such an image? Thanks.

**Comment by pankajgoyal2** [comment]
> I wanted to deploy avalon through k8s and used the scripts in avalon/docker/k8s/fabric/blockchain-connector.yaml.
> This depends on avalon-blockchain-connector-dev image, but I haven't built it.
> '''
> spec:
> containers:
> - image: avalon-blockchain-connector-dev:latest
> name: avalon-blockchain-connector
> '''
> How to build such an image? Thanks.

In order to build the images please follow the https://github.com/hyperledger/avalon/blob/master/docker/k8s/fabric/README.md
Also, I would like to point out that due to recent changes, image built name would be "avalon-fabric-connector-dev" so please rename the image name in the pod/container definition for  blockchain-connector.yaml. I will rectify this and will raise a PR.
Let us know if it doesn't work for you.

**Comment by manju956** [comment]
Closing the issue as it was resolved by @pankajgoyal2
